[package]
edition = "2021"
name = "private_publication_integrity"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "private_publication_integrity"

[dependencies]
serde = "1"
derive_more = "0"

hdi = "0.0.14"
